---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: contour
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  healthChecks:
  - kind: Deployment
    name: contour
    namespace: projectcontour
  - kind: DaemonSet
    name: envoy
    namespace: projectcontour
  interval: 1m0s
  path: ./infrastructure/contour
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client

