---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workloads
  namespace: flux-system
spec:
  dependsOn:
  - name: flagger
  interval: 1m0s
  path: ./workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

